users/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from .views import(
    StudentListView,
    StudentDetailView,
    StudentCreateView,
    StudentDeleteView,
    StudentUpdateView,
    TeacherListView,
    TeacherDetailView,
    TeacherCreateView,
    TeacherDeleteView,
    TeacherUpdateView,
    SignUpView,
    TeacherStudentsCreateView,
    StudentSignUpView,
    TeacherSignUpView,
    StudentGradesListView,
    StudentGradesCreateView,
    StudentGradesDeleteView,
    StudentGradesDetailView,
    StudentGradesUpdateView,
    UserStudentListView,
    SubjectListView,
    SubjectDetailView,
    SubjectCreateView,
    SubjectDeleteView,
    SubjectUpdateView,
    SubjectScoresListView,
    SubjectScoresDetailView,
    SubjectScoresCreateView,
    UserSubjectListView,
    TeacherStudentsDetailView,
    StudentGradesListView,
    StudentGradesDetailView,
    StudentGradesView,
    TeacherStudentsDeleteView,
    TeacherStudentsListView,
    CoursesCreateView,
    CoursesDeleteView,
    CoursesDetailView,
    CoursesUpdateView,
    CoursesListView,
    StudentReportsView,
)
#from django.conf import settings

urlpatterns = [
    path('student/grades', StudentGradesView.as_view(), name='teacher-student-grades'),
    path('student/grades/list/', StudentGradesListView.as_view(), name='teacher-student-grades-list'),
    path('student/grades/<int:pk>/', StudentGradesDetailView.as_view(), name='teacher-student-grades-detail'),
    path('student/grades/new/', StudentGradesCreateView.as_view(), name='teacher-student-grades-new'),
    path('student/grades/<int:pk>/update/', StudentGradesUpdateView.as_view(), name='teacher-student-grades-update'),
    path('student/grades/<int:pk>/delete/', StudentGradesDeleteView.as_view(), name='teacher-student-grades-delete'),

    url(r'^student/(?P<pk>[\w-]+)/update/', StudentUpdateView.as_view(), name='student-update'),
    url(r'^student/(?P<pk>[\w-]+)/delete/', StudentDeleteView.as_view(), name='student-delete'),
    url(r'^student/list/', StudentListView.as_view(), name='student-list'),
    url(r'^student/(?P<pk>[\w-]+)/$', StudentDetailView.as_view() , name='student-detail'),
    url(r'^student/reports/view/', views.StudentReportsView , name='student-reports'),
    path('students/reports/upload/', views.UploadReports, name='upload-reports'),

    path('teacher/student/new/', TeacherStudentsCreateView.as_view(), name='link-teacher-student'),
    #path('teacher_student/', TeacherStudentListView.as_view(), name='teacher-student-list'),
    #path('teacher_student/list/', views.teacher_students_list, name='list-teacher-students'),
    path('teacher/student/list/', TeacherStudentsListView.as_view(), name='list-teacher-students'),
    path('teacher/student/<int:pk>/', TeacherStudentsDetailView.as_view(), name='teacher-student-detail'),
    url(r'^teacher/student/(?P<pk>[\w-]+)/delete/', TeacherStudentsDeleteView.as_view(), name='teacher-student-delete'),

    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/student/new/', StudentSignUpView.as_view(), name='student_signup'),
    path('signup/teacher/new/', TeacherSignUpView.as_view(), name='teacher_signup'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),

    url(r'^teacher/list/', TeacherListView.as_view(), name='teacher-list'),
    url(r'^teacher/(?P<pk>[\w-]+)/update/', TeacherUpdateView.as_view(), name='teacher-update'),
    url(r'^teacher/(?P<pk>[\w-]+)/delete/', TeacherDeleteView.as_view(), name='teacher-delete'),
    url(r'^teacher/(?P<pk>[\w-]+)/', TeacherDetailView.as_view(), name='teacher-detail'),

    path('subject/scores', SubjectScoresListView.as_view(), name='subject-scores-list'),
    path('subject/scores/<int:pk>', SubjectScoresDetailView.as_view(), name='subject-scores-detail'),
    url(r'^ajax/load_subjects/$', views.load_subjects, name='ajax_load_subjects'),  # <-- this one here
    #url(r'^subject/select/', views.show_choices, name="career-select"),
    url(r'^subject/scores/new/', SubjectScoresCreateView.as_view(), name="subject-scores-new"),

    path('subject/', SubjectListView.as_view(), name='subject-list'),
    path('subject/new/', SubjectCreateView.as_view(), name='subject-create'),
    path('subject/<int:pk>/', SubjectDetailView.as_view(), name='subject-detail'),
    path('subject/<int:pk>/update/', SubjectUpdateView.as_view(), name='subject-update'),
    path('subject/<int:pk>/delete/', SubjectDeleteView.as_view(), name='subject-delete'),

    path('grading/', views.grades_predictor, name='grades-prediction'),
    url(r'^career/', views.MainView.as_view(), name='career-choices'),
    path('grades/list/', views.grades, name='list-student-grades'),

    path('courses/', views.MainView.as_view(), name="recommend-courses"),
    path('courses/list/', CoursesListView.as_view(), name="list-courses"),
    path('courses/add/', CoursesCreateView.as_view(), name="create-courses"),
    path('courses/<int:pk>/update/', CoursesUpdateView.as_view(), name="course-update"),
    path('courses/<int:pk>/delete/', CoursesDeleteView.as_view(), name="course-delete"),

]

users/models.py
from django.db import models
#from django.contrib.auth.models import User
from PIL import Image
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import AbstractUser, UserManager
from django.utils.html import escape, mark_safe

class User(AbstractUser):
     is_student = models.BooleanField(default=False)
     is_teacher = models.BooleanField(default=False)

     def get_absolute_url(self):
        return reverse('user-detail', kwargs={'pk': self.pk})

class School(models.Model):
    school_name = models.CharField(max_length=60, default='Oakridge International School (Newton Campus)')
    school_id = models.CharField(max_length=8, primary_key=True)
    date_created = models.DateTimeField(default=timezone.now)
    address = models.CharField(max_length=60, default='Nanakramguda Road, Cyberabad, Khajaguda, Manikonda')
    city = models.CharField(max_length=20,default='Hyderabad')
    state = models.CharField(max_length=25, default='Telangana')
    postal_code = models.IntegerField(default=500008)
    country = models.CharField(max_length=15,default='India')

    def __str__(self):
        return self.school_name

    def get_absolute_url(self):
        return reverse('school-detail', kwargs={'pk': self.pk})

class Student(models.Model):
    student_id = models.CharField(max_length=8, primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    school_id = models.ForeignKey(School, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, default='Abhinav')
    last_name = models.CharField(max_length=30, default='Vemuri')
    email = models.CharField(max_length=60, default='abhi@gmail.com')
    grade = models.CharField(max_length=2, default='X')
    gender = models.CharField(max_length=1,default='M')
    section = models.CharField(max_length=1,default='A')
    age = models.CharField(max_length=10,default='14')
    mobile = models.CharField(max_length=14,default='7981764023')
    dob = models.CharField(max_length=14, default='24-05-2004')
    student_absence_days = models.IntegerField(default=0)
    religion = models.CharField(max_length=15,default='Hindu')
    spoken_lang = models.CharField(max_length=20,default='Telugu,English')
    address = models.CharField(max_length=30, default='Lanco Hills 4LH 1504 Manikonda')
    city = models.CharField(max_length=30,default='Hyderabad')
    state = models.CharField(max_length=25,default='Telangana')
    country = models.CharField(max_length=25,default='India')
    date_created = models.DateTimeField(default=timezone.now)
    GPA = models.FloatField(max_length=5, default=0.0)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('student-detail', kwargs={'pk': self.pk})


class Subject(models.Model):
    subject_name = models.CharField(max_length=60)
    subject_desc = models.CharField(max_length=120)
    school_id = models.ForeignKey(School, on_delete=models.CASCADE)
    grade = models.CharField(max_length=2)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "%s" % (self.subject_name)

    def get_absolute_url(self):
        reverse('subject-detail', kwargs={'pk': self.pk})

class Courses(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    course_name=models.CharField(max_length=50)
    course_link=models.CharField(max_length=100)

    def __str__(self):
        return "%s %s %s" % (self.subject, self.course_name,self.course_link)

    def get_absolute_url(self):
        return reverse('course-detail', kwargs={'pk': self.pk})

class SubjectScores(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    subject_score=models.FloatField(max_length=6,default=0.0)
    date_created = models.DateTimeField(default=timezone.now)

    @property
    def fields(self):
        return [f.name for f in self._meta.fields + self._meta.many_to_many]

    def __str__(self):
        #return '%s %s %s %s %s %s %s %s' % (self.student,self.subject1,self.subject2,self.subject3,self.subject4,self.subject5,self.subject6,self.subject7)
        return '%s %s' % (self.student,self.subject)

    def get_absolute_url(self):
        reverse('subject-scores-detail', kwargs={'pk': self.pk})

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True)
    school_id = models.ForeignKey(School, max_length=8, on_delete=models.CASCADE)
    subject_id = models.ForeignKey(Subject, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, default='Ramakrishna')
    last_name = models.CharField(max_length=30, default='Vemuri')
    grade = models.CharField(max_length=2, default='X')
    section = models.CharField(max_length=3,default='A')
    email = models.CharField(max_length=60, default='rkvemuri2000@yahoo.com')
    mobile = models.CharField(max_length=14,default='9000600534')
    spoken_lang = models.CharField(max_length=30,default='Telugu,English,Hindi')
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "%s" %  (self.first_name)

    def get_absolute_url(self):
        return reverse('teacher-detail', kwargs={'pk': self.pk})

class Student_Grades(models.Model):
    student = models.ForeignKey(Student,  on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, max_length=20)
    SA1 = models.FloatField(max_length=6,default=0.0)
    SA2 = models.FloatField(max_length=6,default=0.0)
    SA3 = models.FloatField(max_length=6,default=0.0)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('grade-detail', kwargs={'pk': self.pk})

class Teacher_Students(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('teacher_student_linkup', kwargs={'pk': self.pk})

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/templates/users/courses_detail.html
{% extends "grading/base.html" %}

{% block content %}
{% if user.is_authenticated  %}
    <div class="content-section">
        <h4> Course Details</h4>
        Course Name: {{ course.course_name }} <br>
        Course Link: {{ course.course_link }} <br>
        Subject  :{{ course.subject_id }} <br>
    </div>
    {% if user.is_authenticated and user.is_teacher %}
        <div class="content-section">
            <h3>Edit Information</h3>
            <a class="btn btn-success mb-4" href="{% url 'course-update' courses.pk %}">Update {{ course.course_name }} Details</a>
            {% if user.is_superuser %}
                <a class="btn btn-danger mb-4" href="{% url 'course-delete' courses.pk %}">Delete {{ course.course_name }} </a>
            {% endif %}
        </div>
    {% endif %}

{% endif %}

{% endblock %}

users/templates/users/login.html
{% extends "grading/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login
                    {{ form|crispy }}
                </legend>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Login</button>
                <small class="text-muted ml-2">
                    <a class="btn btn-primary" href="{% url 'password_reset' %}" role="button">Forgot Password</a>
                </small>
            </div>
<!--
            <div >
                <a class="btn btn-primary git" href="{% url 'social:begin' 'github' %}">Login with GitHub</a>
                 <a class="btn btn-primary twitter" href="{% url 'social:begin' 'twitter' %}">Login with Twitter</a>
                 <a class="btn btn-primary fa fa-facebook fb" href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
            </div>
-->
        </form>
        <div class="border-top pt-3">
            <small>Need an Account? <a class="btn btn-primary" href="{% url 'signup' %}">Sign Up Now</a></small>
        </div>
    </div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends "grading/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password
                    {{ form|crispy }}
                </legend>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Request Password Reset</button>
            </div>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "grading/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.userprofile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info
                    {{ u_form|crispy }}
                    {{ p_form|crispy }}
                </legend>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/reports.html
{% extends "grading/base.html" %}
{% block content %}
<form action="{% url 'upload-reports' %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
{% csrf_token %}

<div class="form-group">
    <br>
    <div class="col-4">
        Student&nbsp;ID<input type="input" name="student_id" id="id_student" value = "{{ students.student_id }}" required="True" class="form-control">
    </div>
    <br>
    <div class="col-4">
        Report File:<input type="file" name="pdf_file" id="pdf_file" required="True" class="form-control">
    </div>
    <br>
    <div class="col-4" style="margin-bottom:10px;">
         <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
    </div>
    <p><a href="{% url 'grading-home' %}">Return to home</a></p>
</div>
{% endblock content %}

users/templates/users/student_confirm_delete.html
{% extends "grading/base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Deleting Student
                <h2>Are you sure you want to delete the Student "{{ student.first_name }}"</h2>
                </legend>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'student-detail' student.pk %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/student_form.html
{% extends "grading/base.html" %}
{% load crispy_forms_tags %}

{% block javascript %}
  <script>
    $("#id_username").change(function () {
      var form = $(this).closest("form");
      $.ajax({
        url: form.attr("data-validate-username-url"),
        data: form.serialize(),
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            alert(data.error_message);
          }
        }
      });

    });

  </script>

{% endblock %}

{% block content %}
    <div class="content-section" data-validate-username-url="{% url 'validate_username' %}">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Student Details
                    {{ form|crispy }}
                </legend>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Save</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/student_grades_form.html
{% extends "grading/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{{ course_name }}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Students Grades
                    {{ form|crispy }}
                </legend>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Save Grades</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/student_grades_list.html
{% extends "grading/base.html" %}
{% load render_table from django_tables2 %}
{% block content %}
{% if  table %}
    {% render_table table %}
{% endif %}
{% endblock %}

users/templates/users/student_grades_list1.html
{% extends "grading/base.html" %}
{% load bootstrap4 %}
{% load querystring from django_tables2 %}

{% block "content" %}

{% if table.page %}
  <div class="table-container">
{% endif %}

{% block table %}
    <div class="table-responsive">
        <table class="table table-hover table-bordered table-striped"{% if table.attrs %} {{ table.attrs.as_html }}{% endif %}>
            {% block table.thead %}
            <thead>
                <tr>
                    <th><a href="{% url "teacher-students-grades-new" %}" class="btn btn-small btn-primary dark"><span class="hidden-phone"><i class="fa fa-user-plus"></i> Add Grades</span></a>

                    </th>
                    <th colspan="5">
                        <form method="post" class="form-inline form-search pull-right">
                          {% csrf_token %}
                            <div>
                              <input id="search_form_id" name="search" type="text" class="form-control col-md-3" placeholder="student,subject,SA1,SA2,SA3"{% if search %} value="{{ search }}"{% endif %}>
                              <button type="submit" class="btn btn-small btn-dark"><i class="fa fa-search"></i> Search</button>
                            </div>
                        </form>
                    </th>
                </tr>

              <tr>
                {% for column in table.columns %}
                    {% if column.orderable %}
                    <th {{ column.attrs.th.as_html }}><a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header|title }}</a></th>
                    {% else %}
                    <th {{ column.attrs.th.as_html }}>{{ column.header|title }}</th>
                    {% endif %}
                {% endfor %}
              </tr>
            </thead>
            {% endblock table.thead %}
            {% block table.tbody %}
            <tbody>
                {% for row in table.page.object_list|default:table.rows %} {# support pagination #}
                  {% block table.tbody.row %}
                  <tr class="{% cycle "odd" "even" %}">
                      {% for column, cell in row.items %}
                          <td {{ column.attrs.td.as_html }}>{{ cell }}</td>
                      {% endfor %}
                  </tr>
                  {% endblock table.tbody.row %}
                {% empty %}
                  {% if table.empty_text %}
                  {% block table.tbody.empty_text %}
                  <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                  {% endblock table.tbody.empty_text %}
                  {% endif %}
                {% endfor %}
            </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            <tfoot></tfoot>
            {% endblock table.tfoot %}
        </table>
    </div>
{% endblock table %}

{% if table.page %}
    {% block pagination %}
        {% bootstrap_pagination table.page url=request.get_full_path %}
    {% endblock pagination %}
  </div>
{% endif %}


{% endblock "content" %}

users/templates/users/subject_detail.html
{% extends "grading/base.html" %}
{% load render_table from django_tables2 %}
{% block content %}
{% if user.is_authenticated %}
    <div class="content-section">
        <h4> Subject Details</h4>
        Subject Name: {{ subject.subject_name }} <br>
        Subject Description: {{ subject.subject_desc }} <br>
        School  :{{ subject.school_id }} <br>
        Grade : {{ subject.grade }} <br>
    </div>
    {% if user.is_superuser %}
        <div class="content-section">
            <h3>Manage Subjects</h3>
            <a class="btn btn-success mb-4" href="{% url 'subject-update' object.id %}">Update {{ subject.subject_name }} Details</a>
            <a class="btn btn-danger mb-4" href="{% url 'subject-delete' object.id %}">Delete {{ subject.subject_name }} Subject</a>
        </div>
    {% endif %}
{% endif %}

{% endblock %}

users/templates/users/subject_form.html
{% extends "grading/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add Subjects
                    {{ form|crispy }}
                </legend>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Save</button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/teacher_detail.html
{% extends "grading/base.html" %}

{% block content %}
{% if user.is_authenticated and user.is_teacher or user.is_superuser %}
    <div class="content-section">
        <h4> Teacher Details</h4>
        Teacher First Name: {{ teacher.first_name }} <br>
        Teacher Last Name: {{ teacher.last_name }} <br>
        School  :{{ teacher.school_id }} <br>
        Grade : {{ teacher.grade }} <br>
    </div>

    <div class="content-section">
        <h3>Edit Information</h3>
        <a class="btn btn-success mb-4" href="{% url 'teacher-update' teacher.pk %}">Update {{ teacher.first_name }} Details</a>
        {% if user.is_superuser %}
            <a class="btn btn-danger mb-4" href="{% url 'teacher-delete' teacher.pk %}">Delete {{ teacher.first_name }} Details</a>
        {% endif %}
    </div>

{% endif %}

{% endblock %}

users/templates/users/teacher_students_detail.html
{% extends "grading/base.html" %}

{% block content %}
{% if user.is_authenticated %}

    <div class="content-section">
        <h3>Teacher Details</h3>
        First Name: {{ teacher_students.teacher.first_name }} <br>
        Last Name: {{ teacher_students.teacher.last_name }} <br>
        School  :{{ teacher_students.school.school_name }} <br>
        Grade : {{ teacher_students.teacher.grade }} <br>
    </div>
{% endif %}
{% if user.is_superuser %}
    <div class="content-section">
        <h3>Manage Students</h3>
        <a class="btn btn-danger mb-4" href="{% url 'teacher-student-delete' object.id %}">Delink {{ teacher_students.student_id }} Student ID</a>
    </div>
{% endif %}
{% endblock %}